#!/bin/bash
# 2017-01-25  Axel Aigle

#
#
# Map_AOA_to_clusters_name 
#
# install BLAST+ from https://www.ncbi.nlm.nih.gov/books/NBK279671/
# Make database (at the roots)
# bin/makeblastdb -in ./path/to/the/directory/Database_amoA_AOA_gap_with_cluster_name.fasta -input_type fasta -dbtype nucl -title amoA_AOA 
#
# set "list-of-your-samples-names": if your samples are named, list them between "in" and ";" as SampleA SampleB SampleC etc., if your samples are numbered just type {0..n} between "in" and ";"
#
# Ensure that you have the List_AOA_Cluster.tab in your directory
# When the script is completed, type: paste List_AOA_Cluster_with_header.tab Calcul_Blast_AOA_gap_cluster_DB_*.tab > AOA_map_to_cluster_name.tab


for sample in list-of-your-samples-names ; do
  blastn -max_target_seqs 1 -query ${sample}_Reads_non_singletons_gap.fasta -db Database_amoA_AOA_gap_with_cluster_name.fasta -outfmt 6 > Blast_AOA_gap_cluster_DB_${sample}.tab
  awk -F '[\t]' '{print $2}' Blast_AOA_gap_cluster_DB_${sample}.tab > Blast_AOA_gap_cluster_DB_${sample}_1.tab
  awk -F '[_]' '{print $1}' Blast_AOA_gap_cluster_DB_${sample}_1.tab > Blast_AOA_gap_cluster_DB_${sample}_2.tab
  awk -F '[;]' '{print $2}' Blast_AOA_gap_cluster_DB_${sample}.tab > Blast_AOA_gap_cluster_DB_${sample}_3.tab
  awk -F '[=]' '{print $2}' Blast_AOA_gap_cluster_DB_${sample}_3.tab > Blast_AOA_gap_cluster_DB_${sample}_4.tab
  paste Blast_AOA_gap_cluster_DB_${sample}_2.tab Blast_AOA_gap_cluster_DB_${sample}_4.tab > Blast_AOA_gap_cluster_DB_${sample}_5.tab
  awk '{sums[$1] += $2} END { for (i in sums) printf("%s %s\n", i, sums[i])}' Blast_AOA_gap_cluster_DB_${sample}_5.tab > Blast_AOA_gap_cluster_DB_${sample}_6.tab
  awk -F " " '{print $2, $1}' OFS='\t' Blast_AOA_gap_cluster_DB_${sample}_6.tab > Blast_AOA_gap_cluster_DB_${sample}_7.tab
  awk 'NR==FNR {h[$2] = $1; next} {print $1, h[$1]}' OFS='\t' Blast_AOA_gap_cluster_DB_${sample}_7.tab List_AOA_Cluster.tab > Blast_AOA_gap_cluster_DB_${sample}_8.tab
  sed '1i Match_base_id\tAbundances-AOA-'${sample}'' Blast_AOA_gap_cluster_DB_${sample}_8.tab > Blast_AOA_gap_cluster_DB_${sample}_9.tab
  sed '1i Match_base_id' List_AOA_Cluster.tab > List_AOA_Cluster_with_header.tab
  awk -F "\t" '{print $2}' Blast_AOA_gap_cluster_DB_${sample}_9.tab > Calcul_Blast_AOA_gap_cluster_DB_${sample}.tab
  rm Blast_AOA_gap_cluster_DB_${sample}_*.tab
  mkdir Blast_db
  mkdir Map_AOA_to_clusters_names
  mv Blast_AOA_gap_cluster_DB_${sample}.tab Blast_db
  mv Calcul_Blast_AOA_gap_cluster_DB_${sample}.tab Map_AOA_to_clusters_names
done


