#!/bin/bash
# 2017-09 Axel Aigle

#
# Script_3_assembly
# 
# set "list-of-your-samples-names": if your samples are named, list them as "A B C" etc., if your samples are numbered just type {0..n} instead of "list-of-your-samples-names"

for sample in list-of-your-samples-names ; do
    gunzip -c ${sample}_F_filt.fastq.gz > ${sample}_R1.fastq
    gunzip -c ${sample}_R_filt.fastq.gz > ${sample}_R2.fastq
    pear -f ${sample}_R1.fastq -r ${sample}_R2.fastq -o ${sample}-assembly 
    seqtk seq -a ${sample}-assembly.assembled.fastq > ${sample}-assembly.fasta
    usearch -fastx_truncate ${sample}-assembly.fasta -trunclen 448 -fastaout ${sample}-assembly_1.fasta
    fasta2tab ${sample}-assembly_1.fasta > ${sample}-assembly_1.tab
    awk -F "\t" '{print $1}' ${sample}-assembly_1.tab > ${sample}-assembly_2.tab
    awk 'BEGIN {FS="/t" } NR { $1=NR} { print}' ${sample}-assembly_2.tab > ${sample}-assembly_3.tab
    sed 's/^/>AOB-'${sample}'-/' ${sample}-assembly_3.tab > ${sample}-assembly_4.tab
    awk -F "\t" '{print $2}' ${sample}-assembly_1.tab > ${sample}-assembly_5.tab
    paste ${sample}-assembly_4.tab ${sample}-assembly_5.tab > ${sample}-assembly_6.tab
    tab2fasta ${sample}-assembly_6.tab > ${sample}-assembly_6.fasta
    usearch -cluster_fast ${sample}-assembly_6.fasta -id 1 -centroids Assembly-${sample}_id_1.fasta -sizeout 
    transeq -sequence Assembly-${sample}_id_1.fasta -outseq Assembly-${sample}_id_1_1.fasta -frame 3 -table 11 -clean
    grep -v X Assembly-${sample}_id_1_1.fasta > Assembly-${sample}_id_1_2.fasta
    usearch -fastx_truncate Assembly-${sample}_id_1_2.fasta -trunclen 149 -fastaout Assembly-${sample}_id_1_3.fasta
    sed 's/^\(>.*\)$/\1_3/' Assembly-${sample}_id_1.fasta > Assembly-${sample}_id_1_4.fasta
    fasta2tab Assembly-${sample}_id_1_4.fasta > Assembly-${sample}_id_1_4.tab
    sed 's/AOB/>AOB/' Assembly-${sample}_id_1_4.tab > Assembly-${sample}_id_1_5.tab
    grep '^>' Assembly-${sample}_id_1_3.fasta > Assembly-${sample}_id_1_3.tab   
    awk -F "\t" '{print $2}' Assembly-${sample}_id_1_5.tab > Assembly-${sample}_id_1_6.tab
    awk -F "\t" '{print $1}' Assembly-${sample}_id_1_5.tab > Assembly-${sample}_id_1_7.tab
    paste Assembly-${sample}_id_1_6.tab Assembly-${sample}_id_1_7.tab > Assembly-${sample}_id_1_8.tab
    awk 'NR==FNR {h[$2] = $1; next} {print $1, h[$1]}' OFS='\t' Assembly-${sample}_id_1_8.tab Assembly-${sample}_id_1_3.tab > Assembly-${sample}_id_1_9.tab
    awk -F '\t' '{print $1}' Assembly-${sample}_id_1_9.tab > Assembly-${sample}_id_1_10.tab
    awk -F '\t' '{print $2}' Assembly-${sample}_id_1_9.tab > Assembly-${sample}_id_1_11.tab 
    sed 's/_3//' Assembly-${sample}_id_1_10.tab > Assembly-${sample}_id_1_12.tab
    paste Assembly-${sample}_id_1_12.tab Assembly-${sample}_id_1_11.tab > Assembly-${sample}_id_1_13.tab
    tab2fasta Assembly-${sample}_id_1_13.tab > Assembly_trans-${sample}_id_1.fasta
    usearch -unoise3 Assembly_trans-${sample}_id_1.fasta -zotus ${sample}_zotus.fasta -tabbedout ${sample}_unoise3.txt -minsize 2
    fasta2tab ${sample}_zotus.fasta > ${sample}_zotus.tab
    sed 's/Zotu/amp/' ${sample}_zotus.tab > ${sample}_zotus_1.tab
    awk -F '\t' '{print $1, $3}' OFS='\t' ${sample}_unoise3.txt > ${sample}_unoise3_1.tab
    awk 'NR==FNR {h[$2] = $1; next} {print $1, h[$1]}' OFS='\t' ${sample}_unoise3_1.tab ${sample}_zotus_1.tab > ${sample}_list_non_singletons.tab
    awk -F '\t' '{print $2}' ${sample}_list_non_singletons.tab > ${sample}_list_non_singletons_1.tab
    fasta2tab Assembly_trans-${sample}_id_1.fasta > ${sample}_valids_reads_id_1.tab
    awk -F '\t' '{print $2, $1}' OFS='\t' ${sample}_valids_reads_id_1.tab > ${sample}_valids_reads_id_1_1.tab
    awk 'NR==FNR {h[$2] = $1; next} {print $1, h[$1]}' OFS='\t' ${sample}_valids_reads_id_1_1.tab ${sample}_list_non_singletons_1.tab > ${sample}_Reads_non_singletons.tab
    tab2fasta ${sample}_Reads_non_singletons.tab > ${sample}_Reads_non_singletons.fasta
    mkdir Intermediate_reads
    rm *.tab
    rm *.txt
    rm ${sample}-assembly.fasta
    rm ${sample}-assembly_*.fasta
    rm Assembly-${sample}_id_1_*.fasta
    mv ${sample}_*.fastq.gz DADA2_filtered
    mv Assembly-${sample}_id_1.fasta Intermediate_reads
    mv Assembly_trans-${sample}_id_1.fasta Intermediate_reads
    rm ${sample}_R*.fastq
    rm ${sample}_zotus.fasta
    rm ${sample}-assembly.unassembled.forward.fastq
    rm ${sample}-assembly.unassembled.reverse.fastq
    rm ${sample}-assembly.discarded.fastq
    rm ${sample}-assembly.assembled.fastq
done
